### ISSUE TITLE
[REQUEST] Fluid output

### ISSUE THREAD

**Issue by DevTimur** [realmayus/YouMatter#12]
U-matter should be automatically exported to nearby fluid tanks. (maybe with configurable side, like in Thermal Exp, or a simple button to turn ON/OFF auto-export). Should preffer Replicator, if it placed next to it.

**Comment by realmayus** [comment]
Good idea, thanks, will implement that in the next release!

**Comment by realmayus** [comment]
Implemented in Release 1.3, now available on CurseForge
