### ISSUE TITLE
Items in YouMatter machines are disappearing after reloading world

### ISSUE THREAD

**Issue by Agmsitrial** [realmayus/YouMatter#18]
When exiting and entering my save i noticed that items in machines are vanished. There was thumb drive in encoder, dragon heart from DE in scanner, another thumb drive in replicator, bucket with stabilizer in matter creator. And after reloading the world all those things are gone.
Breaking and placing machines again does nothing.

**Comment by realmayus** [comment]
Thank you for reporting. I’ll look into this ASAP.

**Comment by realmayus** [comment]
Are there any errors or crashlogs? @Agmsitrial

**Comment by realmayus** [comment]
Again, thank you very much for filing this bug report. This was a major bug that shouldn't happen.
I fixed it along with other stuff in [Release 1.5 which you can download here](https://www.curseforge.com/minecraft/mc-mods/youmatter/files/2878281) @Agmsitrial
