### ISSUE TITLE
Crash with the U-gen

### ISSUE THREAD

**Issue by Taccio33** [realmayus/YouMatter#24]
as said: pulling from the u-generator with something that is not a conduit from enderio or cyclic (such as extrautilit2 or translocator) crashes the game, tested on 1.2-1.3-1.4-1.5.
some crashes:
[crash-2020-02-09_23.02.30-client.txt](https://github.com/realmayus/YouMatter/files/4178110/crash-2020-02-09_23.02.30-client.txt)
[crash-2020-02-09_22.59.06-client.txt](https://github.com/realmayus/YouMatter/files/4178111/crash-2020-02-09_22.59.06-client.txt)
[crash-2020-02-09_22.09.19-client.txt](https://github.com/realmayus/YouMatter/files/4178112/crash-2020-02-09_22.09.19-client.txt)
[crash-2020-02-08_17.09.37-server.txt](https://github.com/realmayus/YouMatter/files/4178113/crash-2020-02-08_17.09.37-server.txt)
[crash-2020-02-08_14.14.35-server.txt](https://github.com/realmayus/YouMatter/files/4178114/crash-2020-02-08_14.14.35-server.txt)
[crash-2020-02-08_00.19.33-server.txt](https://github.com/realmayus/YouMatter/files/4178115/crash-2020-02-08_00.19.33-server.txt)
[crash-2020-02-08_00.06.13-server.txt](https://github.com/realmayus/YouMatter/files/4178116/crash-2020-02-08_00.06.13-server.txt)

**Comment by realmayus** [comment]
Thanks for the report, will look into it.

**Comment by realmayus** [comment]
I’ll fix this today.

**Comment by realmayus** [comment]
Updated in Release 1.12.2-1.6
https://www.curseforge.com/minecraft/mc-mods/youmatter/files/2880880
