### ISSUE TITLE
Adjust u-matter creation/usage

### ISSUE THREAD

**Issue by MUHAKLorTheDorfTrottel4Github** [realmayus/YouMatter#37]
mc 1.15.2
forge-1.15.2-31.1.12
youmatter-1.15.2-1.9

to replicate a Project-E  >Klein-Star-Omega< it just needs 1 bucket u-matter
Klein-Star-Omega is 25 Mill EMC , which are 3000 diamonds or 25000 coal or
100000 buckets of stabilizer 

to balace more I suggest:
make u-mater production extreme expensive ( much more power needed ),
which in my opinion the fastest and easyest way
or 
adjust the needed  amount of u-matter needed for  specific items ( boaring)

energy in end-game can easely produced by Mekanism reactor ( 800kFE/tick),
so I suggest at least **500kFE fo 1 millibucket U-MATTER**

at time beeing  you can create a "perpedum mobile" using projectE, mekanism and youmatter

regards

**Comment by realmayus** [comment]
This is a task that modpack creators have to do. They can adjust the required U-Matter amount in the config, I can't do much here. I can't define a U-Matter amount for any item in the world.

**Comment by realmayus** [comment]
See the overrides field in the config of the mod.

**Comment by MUHAKLorTheDorfTrottel4Github** [comment]
I'm not running a modpack, just single play with some mods
its in my opinion just much to cheep to create U-MATTER

as Mod creator I would adjust the amount of energy drasticallyan and add a config option

but its up to you, I'm just a stupid squarehead which is not able to write mods 

greetings

**Comment by realmayus** [comment]
Yes, I can add a config option for the required energy. Even for single player, you can adjust the config. There, you can set an override so that this expensive item costs more U-Matter than other items.

**Comment by MUHAKLorTheDorfTrottel4Github** [comment]
please do (energy) , that would be the easiest way for all of us 

regards
