### ISSUE TITLE
Setting to include NBT Data when scanning item

### ISSUE THREAD

**Issue by realmayus** [realmayus/YouMatter#8]

**Comment by DevTimur** [comment]
That would make replicator a DUPE machine. You can scan Stronghold Box with all the content inside, and replicate it with all the items in cost of empty Box.
I strongly disagree to implement NBT copying.

**Comment by DevTimur** [comment]
Ofcourse, some modded machines strongly rely on NBT, for example Thermal Expansion machines store all upgrade and machine tier in NBT data, so copying in will result in lvl 1 machine witout ANY upgrade. (Newly crafted machine comes with NBT data from begining). Or for example Mekanism machines, they do same thing, level and upgrades stored in NBT. But personally I think NBT coppying is a BAD thing to implement. Even with Blacklist of items it would be a hussle to add all the potential things you can use to dupe stuff.

**Comment by realmayus** [comment]
Yeah, you got a point. I'll reconsider it first. If I were to implement it, I'd make it an option in the config that's disabled by default.

**Comment by realmayus** [comment]
Closed because @DevTimur has a very good point :)
Cloning whole crates/drawers would be too overpowered
