### ISSUE TITLE
Bug with Ender-IO conduits

### ISSUE THREAD

**Issue by thewawpro** [realmayus/YouMatter#9]
![2020-02-06_19 24 00](https://user-images.githubusercontent.com/52713206/73971171-4e4d0500-4916-11ea-8034-d619b6fc5565.png)
![2020-02-06_19 24 02](https://user-images.githubusercontent.com/52713206/73971174-4f7e3200-4916-11ea-8446-c335756c2446.png)
![2020-02-06_19 24 08](https://user-images.githubusercontent.com/52713206/73971178-5016c880-4916-11ea-8860-cf44889f3ef9.png)

Pulls out the Item from the display.
Even whenpaused.

Love the mod.

**Comment by realmayus** [comment]
Thank you very much for your bug report! Means a lot! I am currently looking into the issue and will release a fixed version.

**Comment by realmayus** [comment]
Fixed in [Version 1.2](https://www.curseforge.com/minecraft/mc-mods/youmatter/files/2876319)

**Comment by thewawpro** [comment]
Thanks for the Fix, this mod is so useful for me.

**Comment by realmayus** [comment]
You're welcome! Glad you like the mod :)
